In [1]:
import pandas as pd
from pathlib import Path
from src.features.create_features import add_previous_day, add_previous_2w_mean, add_weather

In [2]:
df_o3 = pd.read_csv(Path("./data/processed/merged_o3_trafic_weather_daily.csv"))
df_pm10 = pd.read_csv(Path("./data/processed/merged_pm10_trafic_weather_daily.csv"))

In [3]:
df_o3

,date,code_site,concentration,avg_debit,avg_taux_occup,RR,TNTXM,FFM,PMERM,GLOT,UM
0,2021-01-01,FR04004,35.0,523.403488,3.222381,0.055556,1.833333,2.033333,1011.3,386.0,83.0
1,2021-01-01,FR04017,34.9,494.989194,2.114353,0.055556,1.833333,2.033333,1011.3,386.0,83.0
2,2021-01-01,FR04037,37.1,450.788817,2.498502,0.055556,1.833333,2.033333,1011.3,386.0,83.0
3,2021-01-01,FR04055,40.4,261.828871,2.365695,0.055556,1.833333,2.033333,1011.3,386.0,83.0
4,2021-01-02,FR04004,10.7,658.445692,5.319976,0.088889,1.566667,1.600000,1014.8,465.0,88.0
...,...,...,...,...,...,...,...,...,...,...,...
4351,2023-12-30,FR04055,55.9,469.473481,6.305843,0.900000,9.216667,6.066667,1013.4,186.5,87.0
4352,2023-12-31,FR04004,84.6,1015.223434,6.947408,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4353,2023-12-31,FR04017,83.6,786.605914,6.214364,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4354,2023-12-31,FR04037,82.8,690.260033,4.646041,0.050000,9.650000,8.466667,1002.3,429.0,73.0
4355,2023-12-31,FR04055,81.6,430.735652,5.769500,0.050000,9.650000,8.466667,1002.3,429.0,73.0

In [6]:
df_o3 = add_previous_day(df_o3)
df_o3 = add_previous_2w_mean(df_o3)
df_o3 = add_weather(df_o3)

df_pm10 = add_previous_day(df_pm10)
df_pm10 = add_previous_2w_mean(df_pm10)
df_pm10 = add_weather(df_pm10)
df_o3.head(50)

,date,code_site,concentration,avg_debit,avg_taux_occup,RR,TNTXM,FFM,PMERM,GLOT,UM,previous_day,previous_2w_mean,next_RR,next_TNTXM,next_FFM,next_PMERM,next_GLOT,next_UM
0,2021-01-01,FR04004,35.0,523.403488,3.222381,0.055556,1.833333,2.033333,1011.3,386.0,83.0,NaN,NaN,0.088889,1.566667,1.600000,1014.8,465.0,88.0
4,2021-01-02,FR04004,10.7,658.445692,5.319976,0.088889,1.566667,1.600000,1014.8,465.0,88.0,35.0,35.000000,0.088889,3.083333,3.000000,1014.2,194.5,84.0
8,2021-01-03,FR04004,13.9,618.638847,4.434031,0.088889,3.083333,3.000000,1014.2,194.5,84.0,10.7,22.850000,0.100000,2.816667,4.533333,1013.6,64.0,82.5
12,2021-01-04,FR04004,17.9,761.163550,6.533927,0.100000,2.816667,4.533333,1013.6,64.0,82.5,13.9,19.866667,0.144444,2.566667,4.266667,1014.9,48.5,84.0
16,2021-01-05,FR04004,3.3,826.326407,7.230668,0.144444,2.566667,4.266667,1014.9,48.5,84.0,17.9,19.375000,0.211111,3.166667,3.133333,1016.6,60.5,84.5
20,2021-01-06,FR04004,5.0,854.657763,7.679157,0.211111,3.166667,3.133333,1016.6,60.5,84.5,3.3,16.160000,0.288889,3.050000,2.900000,1017.3,165.0,84.0
24,2021-01-07,FR04004,23.6,811.877922,7.066742,0.288889,3.050000,2.900000,1017.3,165.0,84.0,5.0,14.300000,0.000000,2.850000,2.166667,1018.9,227.5,76.0
28,2021-01-08,FR04004,29.3,887.992664,7.824832,0.000000,2.850000,2.166667,1018.9,227.5,76.0,23.6,15.628571,0.000000,1.433333,4.433333,1023.8,570.5,83.0
32,2021-01-09,FR04004,27.5,736.079598,7.313371,0.000000,1.433333,4.433333,1023.8,570.5,83.0,29.3,17.337500,0.155556,1.716667,2.933333,1025.7,565.5,84.5
36,2021-01-10,FR04004,37.4,652.550643,5.484262,0.155556,1.716667,2.933333,1025.7,565.5,84.5,27.5,18.466667,0.733333,2.850000,4.066667,1023.6,162.0,83.5
40,2021-01-11,FR04004,39.8,810.480804,7.363003,0.733333,2.850000,4.066667,1023.6,162.0,83.5,37.4,20.360000,5.500000,7.033333,6.066667,1017.1,141.5,87.5
44,2021-01-12,FR04004,53.4,829.871983,8.730301,5.500000,7.033333,6.066667,1017.1,141.5,87.5,39.8,22.127273,2.188889,7.666667,5.400000,1020.9,124.5,90.0
48,2021-01-13,FR04004,64.9,833.139272,8.816350,2.188889,7.666667,5.400000,1020.9,124.5,90.0,53.4,24.733333,3.177778,9.933333,7.533333,1016.5,191.0,85.0
52,2021-01-14,FR04004,68.4,875.421208,8.660865,3.177778,9.933333,7.533333,1016.5,191.0,85.0,64.9,27.823077,0.044444,2.300000,5.266667,1027.7,401.0,73.0
56,2021-01-15,FR04004,48.5,880.533412,8.678065,0.044444,2.300000,5.266667,1027.7,401.0,73.0,68.4,30.721429,10.322222,2.516667,2.400000,1024.8,82.5,84.5
60,2021-01-16,FR04004,28.1,654.230258,5.395083,10.322222,2.516667,2.400000,1024.8,82.5,84.5,48.5,31.685714,0.933333,4.500000,2.250000,1024.6,385.0,83.0
64,2021-01-17,FR04004,50.9,632.807250,5.668334,0.933333,4.500000,2.250000,1024.6,385.0,83.0,28.1,32.928571,0.233333,5.333333,2.400000,1026.5,500.5,79.5
68,2021-01-18,FR04004,59.3,820.537817,7.735396,0.233333,5.333333,2.400000,1026.5,500.5,79.5,50.9,35.571429,3.177778,6.083333,4.350000,1014.8,219.5,80.5
72,2021-01-19,FR04004,64.1,826.364276,8.603390,3.177778,6.083333,4.350000,1014.8,219.5,80.5,59.3,38.528571,5.922222,9.050000,5.400000,998.9,387.0,58.5
76,2021-01-20,FR04004,73.0,869.574301,8.630010,5.922222,9.050000,5.400000,998.9,387.0,58.5,64.1,42.871429,11.522222,7.983333,5.750000,993.0,165.5,82.5
80,2021-01-21,FR04004,80.9,753.088666,8.901229,11.522222,7.983333,5.750000,993.0,165.5,82.5,73.0,47.728571,0.066667,6.450000,3.433333,996.3,481.5,82.0
84,2021-01-22,FR04004,63.0,679.033705,7.920905,0.066667,6.450000,3.433333,996.3,481.5,82.0,80.9,51.821429,4.788889,4.383333,5.666667,996.3,185.5,86.5
88,2021-01-23,FR04004,52.9,744.009094,7.021297,4.788889,4.383333,5.666667,996.3,185.5,86.5,63.0,54.228571,2.511111,1.500000,5.850000,1000.9,154.0,85.0
92,2021-01-24,FR04004,65.2,656.761686,4.786974,2.511111,1.500000,5.850000,1000.9,154.0,85.0,52.9,56.042857,0.288889,3.666667,7.450000,1009.8,489.0,74.5
96,2021-01-25,FR04004,67.5,787.816779,8.228086,0.288889,3.666667,7.450000,1009.8,489.0,74.5,65.2,58.028571,3.477778,2.833333,6.250000,1021.3,332.0,70.0
100,2021-01-26,FR04004,47.9,838.251569,8.513747,3.477778,2.833333,6.250000,1021.3,332.0,70.0,67.5,60.007143,7.444444,6.500000,5.350000,1015.3,122.0,92.5
104,2021-01-27,FR04004,48.5,840.364251,8.924501,7.444444,6.500000,5.350000,1015.3,122.0,92.5,47.9,59.614286,3.688889,11.183333,6.666667,1007.7,350.0,87.5
108,2021-01-28,FR04004,60.1,855.222853,8.725482,3.688889,11.183333,6.666667,1007.7,350.0,87.5,48.5,58.442857,8.744444,10.900000,7.666667,1005.0,387.5,75.5
112,2021-01-29,FR04004,79.2,818.592725,9.217612,8.744444,10.900000,7.666667,1005.0,387.5,75.5,60.1,57.850000,6.877778,10.400000,4.300000,996.9,404.5,87.0
116,2021-01-30,FR04004,65.0,780.423965,7.466901,6.877778,10.400000,4.300000,996.9,404.5,87.0,79.2,60.042857,7.211111,7.933333,2.500000,995.2,189.0,94.0
120,2021-01-31,FR04004,47.3,679.309280,5.659632,7.211111,7.933333,2.500000,995.2,189.0,94.0,65.0,62.678571,2.555556,9.083333,4.700000,997.0,195.0,82.0
124,2021-02-01,FR04004,61.1,842.666757,7.077962,2.555556,9.083333,4.700000,997.0,195.0,82.0,47.3,62.421429,1.677778,10.800000,6.000000,1002.2,446.0,80.5
128,2021-02-02,FR04004,62.9,760.150906,6.999028,1.677778,10.800000,6.000000,1002.2,446.0,80.5,61.1,62.550000,7.144444,11.000000,6.800000,1002.2,368.0,81.0
132,2021-02-03,FR04004,71.7,850.492048,8.738896,7.144444,11.000000,6.800000,1002.2,368.0,81.0,62.9,62.464286,0.033333,8.883333,3.333333,1011.8,433.5,84.5
136,2021-02-04,FR04004,54.8,902.865060,8.229306,0.033333,8.883333,3.333333,1011.8,433.5,84.5,71.7,62.371429,1.966667,9.566667,2.600000,1011.2,479.5,84.0
140,2021-02-05,FR04004,61.7,734.594850,8.549830,1.966667,9.566667,2.600000,1011.2,479.5,84.0,54.8,60.507143,17.511111,8.116667,3.700000,1003.3,98.0,92.5
144,2021-02-06,FR04004,53.6,799.125952,7.074213,17.511111,8.116667,3.700000,1003.3,98.0,92.5,61.7,60.414286,1.700000,2.916667,4.200000,998.2,93.0,84.5
148,2021-02-07,FR04004,44.6,715.520663,5.222048,1.700000,2.916667,4.200000,998.2,93.0,84.5,53.6,60.464286,0.000000,-0.616667,2.833333,999.4,91.5,78.5
152,2021-02-08,FR04004,45.7,887.498605,7.280506,0.000000,-0.616667,2.833333,999.4,91.5,78.5,44.6,58.992857,1.533333,-2.233333,4.200000,1003.4,96.5,81.5
156,2021-02-09,FR04004,33.8,925.959084,7.851453,1.533333,-2.233333,4.200000,1003.4,96.5,81.5,45.7,57.435714,0.000000,-3.450000,5.866667,1011.9,919.5,69.5
160,2021-02-10,FR04004,51.0,784.461353,7.408415,0.000000,-3.450000,5.866667,1011.9,919.5,69.5,33.8,56.428571,0.000000,-2.200000,5.833333,1025.5,926.0,62.0
164,2021-02-11,FR04004,60.6,775.205796,9.079728,0.000000,-2.200000,5.833333,1025.5,926.0,62.0,51.0,56.607143,0.022222,-1.133333,6.166667,1026.6,710.0,54.5
168,2021-02-12,FR04004,62.3,864.240066,8.631474,0.022222,-1.133333,6.166667,1026.6,710.0,54.5,60.6,56.642857,0.022222,-2.416667,5.233333,1032.8,990.5,49.0
172,2021-02-13,FR04004,54.6,784.242975,7.640113,0.022222,-2.416667,5.233333,1032.8,990.5,49.0,62.3,55.435714,0.588889,-0.550000,6.100000,1031.9,824.0,55.5
176,2021-02-14,FR04004,59.4,728.514006,5.618180,0.588889,-0.550000,6.100000,1031.9,824.0,55.5,54.6,54.692857,0.377778,5.450000,5.133333,1025.8,340.0,72.0
180,2021-02-15,FR04004,40.4,855.662755,7.725122,0.377778,5.450000,5.133333,1025.8,340.0,72.0,59.4,55.557143,1.011111,9.083333,5.533333,1017.9,591.5,76.5
184,2021-02-16,FR04004,64.8,867.614492,7.827256,1.011111,9.083333,5.533333,1017.9,591.5,76.5,40.4,54.078571,0.000000,10.733333,5.066667,1018.5,647.0,79.5
188,2021-02-17,FR04004,67.3,935.827450,7.893061,0.000000,10.733333,5.066667,1018.5,647.0,79.5,64.8,54.214286,6.844444,8.733333,5.900000,1011.2,233.5,81.0
192,2021-02-18,FR04004,57.3,873.134452,8.255327,6.844444,8.733333,5.900000,1011.2,233.5,81.0,67.3,53.900000,0.000000,9.883333,4.333333,1015.1,602.0,85.0
196,2021-02-19,FR04004,52.1,895.795525,8.069607,0.000000,9.883333,4.333333,1015.1,602.0,85.0,57.3,54.078571,0.000000,13.150000,7.033333,1010.7,968.0,64.0

In [7]:
df_o3 = df_o3.reset_index(drop=True)
df_pm10 = df_pm10.reset_index(drop=True)

In [8]:
df_o3.to_csv(Path("./data/processed/merged_o3_trafic_weather_features.csv"), index=False)
df_pm10.to_csv(Path("./data/processed/merged_pm10_trafic_weather_features.csv"), index=False)